#!/usr/bin/env python3
"""Collect the week-2 CodeFormer evidence into one markdown report (reports/quality/codeformer_week2.md).

Inputs (all produced by the other scripts, nothing is recomputed here):
  /tmp/dabai_quality/codeformer/codeformer_profile_<id>_baseline.json   legacy CLI + instrumented breakdown (codeformer_profile.py)
  /tmp/dabai_quality/codeformer/bench.json                              micro-benchmarks (codeformer_bench.py)
  /tmp/dabai_quality/codeformer/landmark_check.json                     landmark reuse measurement (codeformer_landmark_check.py)
  /tmp/dabai_quality/candidates/<id>_<tag>.manifest.json + .nvsmi.log  E2E video-stage candidates (run_codeformer_ab.sh)
  /tmp/dabai_quality/manifests/<id>_<tag>.{quality,face_metrics,codeformer_quality}.json
  /tmp/dabai_quality/manifests/<id>_baseline.quality.json               SyncNet before
    python scripts/quality/codeformer_report.py --candidates 04:cf_w05,cf_w07,cf_w09,cf_w10,cf_w05_fp16,cf_w05_retina 01:cf_w05 ... --out reports/quality/codeformer_week2.md
"""
from __future__ import annotations
import argparse, json, pathlib, time
Q = pathlib.Path("/tmp/dabai_quality")


def load(p: pathlib.Path):
    return json.loads(p.read_text()) if p.exists() else None


def nvsmi_peak(p: pathlib.Path):
    try:
        return max(int(x) for x in p.read_text().split() if x.strip().isdigit())
    except Exception:
        return None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--profile-id", default="04"); ap.add_argument("--candidates", nargs="+", default=["04:cf_w05"])
    ap.add_argument("--out", default="reports/quality/codeformer_week2.md"); ap.add_argument("--title", default="CodeFormer optimized stage — week 2 results")
    ap.add_argument("--notes", default=None, help="markdown file appended verbatim after the tables (reading / decisions)")
    a = ap.parse_args()
    L = [f"# {a.title} ({time.strftime('%Y-%m-%d')})", "",
         "Scripts: `scripts/optim/codeformer_accel.py` (runner), `scripts/quality/codeformer_profile.py` (legacy profile), `codeformer_landmark_check.py`, "
         "`codeformer_bench.py`, `run_codeformer_ab.sh` -> `candidate_video_stage.py --codeformer optimized` + `quality_manifest.py --syncnet` + `face_metrics.py` + `codeformer_quality.py`. "
         "Raw JSON under `/tmp/dabai_quality/{codeformer,candidates,manifests}` (not tracked). Generated by `codeformer_report.py`.", ""]
    prof = load(Q / "codeformer" / f"codeformer_profile_{a.profile_id}_baseline.json")
    if prof:
        c, i = prof.get("cli"), prof.get("instrumented"); src = prof["source"]
        L += [f"## A. Legacy CodeFormer (`inference_codeformer.py -i {a.profile_id}_baseline.mp4 -w 0.5 -s 1`, {src['width']}x{src['height']} {src['frames']} frames {src['duration_s']} s)", ""]
        if c:
            L += [f"CLI in its own process: **{c['seconds']} s = {c['s_per_video_min']} s/video-min**, peak VRAM {c['peak_device_mib']} MiB, {c['png_files']} PNG files / {c['disk_bytes'] / 2**20:.0f} MB on disk, "
                  f"output geometry {c['output']['width']}x{c['output']['height']} ({'CHANGED' if c['geometry_changed'] else 'preserved'}).", ""]
        if i:
            L += [f"Instrumented in-process replay of the same loop: wall {i['wall_seconds']} s = {i['s_per_video_min']} s/video-min. Breakdown:", "",
                  "| step | s | % | ms/frame |", "|---|---:|---:|---:|"]
            for k, v in sorted(i["steps_seconds"].items(), key=lambda kv: -kv[1]):
                L.append(f"| {k} | {v} | {v / i['wall_seconds'] * 100:.1f} | {i['ms_per_frame'][k]} |")
            L.append("")
    lm = load(Q / "codeformer" / "landmark_check.json")
    if lm:
        L += ["## Landmark reuse (no second detector)", "",
              f"{lm['frames']} sampled master frames (04/01/03). RetinaFace router (full-res) vs the upstream CodeFormer detection (facelib, resize 640) — the SAME detector — "
              f"disagree by median px: " + ", ".join(f"{k} {v['median']}" for k, v in lm["retina_vs_upstream_px"].items()) + ".",
              "Points derived from LatentSync's insightface landmark_2d_106 (already computed for every LATENT_SYNC frame by the verify pass) vs the router: "
              + ", ".join(f"{k} {v['median_px']} px (p95 {v['p95_px']})" for k, v in lm["chosen"].items()) + f"; mean over 5 points median {lm['insight5_vs_retina_mean_px']['median']} px.",
              f"512 crop PSNR: insightface-aligned vs RetinaFace-aligned {lm['crop_psnr_retina_vs_insight']['median']} dB, upstream-RetinaFace vs router-RetinaFace {lm['crop_psnr_retina_vs_upstream']['median']} dB -> "
              "the reused points are within the detector's own frame-to-frame noise. Mapping `LM106_TO_5` = " + json.dumps(lm["LM106_TO_5"]) + ".", ""]
    b = load(Q / "codeformer" / "bench.json")
    if b:
        L += [f"## B/C. In-memory runner micro-benchmarks ({b['frames']} LATENT_SYNC frames of {b['id']}, {b['shape'][1]}x{b['shape'][0]}, w={b['w']}, best of {len(next(iter(b['variants'].values()))['runs'])} runs)", "",
              f"Landmarks: insightface verify pass {b['insightface_detect_ms_per_frame']} ms/frame (already paid by the pipeline) vs a fresh RetinaFace pass {b['retinaface_detect_ms_per_frame']} ms/frame.", "",
              "| variant | config | faces/s | wall s | peak VRAM MiB | net s | parse s | paste s | vs reference PSNR mean/min dB | max abs diff | px>2 / frame |", "|---|---|---:|---:|---:|---:|---:|---:|---|---:|---:|"]
        for name, v in b["variants"].items():
            best = min(v["runs"], key=lambda r: r["wall"]); st = best["stages"]; vr = v.get("vs_reference", {})
            L.append(f"| {name} | {json.dumps(v['config'])} | {v['faces_per_s']} | {v['best_wall']} | {v['peak_vram_mib']} | {st.get('net', st.get('h2d_net', ''))} | {st.get('parse', '')} | {st.get('paste', '')} | "
                     f"{vr.get('psnr_mean', 'ref')}/{vr.get('psnr_min', '')} | {vr.get('max_abs_diff', '')} | {vr.get('pixels_diff_gt2_mean', '')} |")
        u = b.get("upstream_helper_check")
        if u:
            L += ["", f"Upstream `FaceRestoreHelper.align_warp_face / paste_faces_to_input_image` + `net` at batch 1 with the SAME landmarks vs the runner (batch 1): "
                  f"PSNR {u['psnr_mean']} dB mean / {u['psnr_min']} min, max |diff| {u['max_abs_diff']} ({u['frames']} frames) — the runner reproduces the upstream arithmetic; "
                  f"upstream functions unbatched run at {u['faces_per_s_unbatched_upstream_functions']} faces/s."]
        L.append("")
    L += ["## E2E candidates (video stage only, audio reused from the baseline; `candidate_video_stage.py --codeformer optimized`)", "",
          "| video | tag | eligible / master frames | faces restored | fallback det | CF s | CF s/video-min | LS s | stage total s | peak VRAM MiB (nvsmi) | valid | geometry | untouched frames PSNR dB (re-encode) | changed px outside face square (pre-encode) | SyncNet out (LS-only / orig) | AV off | mouth sharp | upper sharp | flicker | eyes sharp vs LS | seam ratio (p95) |",
          "|---|---|---|---:|---:|---:|---:|---:|---:|---:|---|---|---:|---:|---|---:|---:|---:|---:|---:|---|"]
    for spec in a.candidates:
        vid, tags = spec.split(":"); base_q = load(Q / "manifests" / f"{vid}_baseline.quality.json") or {}
        bsn = (base_q.get("syncnet") or {}).get("output", {}).get("confidence"); osn = (base_q.get("syncnet") or {}).get("original", {}).get("confidence")
        for tag in tags.split(","):
            m = load(Q / "candidates" / f"{vid}_{tag}.manifest.json")
            if not m:
                L.append(f"| {vid} | {tag} | missing | | | | | | | | | | | | | | | | | | | |"); continue
            Lp = m["lipsync"]; cfd = Lp.get("codeformer"); st = m["stage_seconds"]; dur = m["source"]["duration_s"]
            q = load(Q / "manifests" / f"{vid}_{tag}.quality.json") or {}; fm = load(Q / "manifests" / f"{vid}_{tag}.face_metrics.json") or {"segments": []}; cq = load(Q / "manifests" / f"{vid}_{tag}.codeformer_quality.json") or {}
            sn = (q.get("syncnet") or {}).get("output", {}); segs = fm["segments"]
            mean = lambda k: round(sum(s[k] for s in segs) / len(segs), 3) if segs else None
            if isinstance(cfd, dict):
                el, tot, cfs = cfd["eligible_frames"], cfd["master_frames"], cfd["seconds"]; faces, fb = cfd["totals"]["faces_restored"], cfd["totals"]["fallback_detections"]
            else:
                el, tot, cfs, faces, fb = sum(s["frames"] for s in Lp["segments"] if s["action"] == "LATENT_SYNC"), Lp["master_frames"], 0.0, 0, 0
            g = cq.get("geometry", {}); un = cq.get("untouched_frames", {}); pre = cq.get("locality_pre_encode") or {}; seam = cq.get("seam", {}); sh = cq.get("sharpness", {})
            L.append(f"| {vid} | {tag} | {el} / {tot} | {faces} | {fb} | {cfs} | {round(cfs / dur * 60, 2)} | {st.get('latentsync')} | {st['total']} | {nvsmi_peak(Q / 'candidates' / f'{vid}_{tag}.nvsmi.log')} | "
                     f"{'PASS' if m['validation']['pass'] else 'FAIL'} | {'same' if g.get('identical') else 'DIFF'} | {un.get('psnr_mean')} | {pre.get('change_outside_square_max_px', 'n/a')} | {sn.get('confidence')} ({bsn} / {osn}) | {sn.get('av_offset_frames')} | "
                     f"{mean('mouth_sharp_ratio')} | {mean('upper_sharp_ratio')} | {mean('flicker_ratio')} | {sh.get('upper_face_ratio_mean')} | {seam.get('ratio_mean')} ({seam.get('ratio_p95')}) |")
    L.append("")
    if a.notes and pathlib.Path(a.notes).exists():
        L += ["", pathlib.Path(a.notes).read_text().rstrip(), ""]
    out = pathlib.Path(a.out); out.parent.mkdir(parents=True, exist_ok=True); out.write_text("\n".join(L) + "\n"); print(f"-> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
